language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t catysomething/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true catysomething/docker-react npm run test -- a
