language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t catysomething/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true catysomething/docker-react npm run test -- a

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: "docker-ci-test"
  env: "DockerCiTest-env"
  bucket_name: "elasticbeanstalk-us-east-2-797302708223"
  bucket_path: "docker-ci-test"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
  